### ISSUE TITLE
검색기능 추가한 풀리퀘스트를 확인하면 파일변경이 db파일만 변경되있습니다.

### ISSUE THREAD

**Issue by ksccmp** [onnoo/hu-oss-sw-2018-B-6#17]

**Comment by onnoo** [comment]
제가 squash merge를 한 결과로 보입니다.
저도 처음으로 써본지라 변경사항에 저렇게 보이는 건 예상 못 했네요.
해당 pull request의 최근 커밋들을 보시면 변경점을 볼 수 있습니다..

**Comment by ksccmp** [comment]
pull을 하면 search관련된건 제 소스트리에 안넘어오는데 저만그런가엽..ㅠ

**Comment by onnoo** [comment]
59b753724d1a74fef2dede5d1d6923853415221b 누락된 search부분 코드를 추가했습니다.
merge 할 때 squash와 rebase를 좀 더 알아보겠습니다.
